### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by wangsongiam** [reasonml/reason-cli#28] opened 2017-04-30 20:01 UTC
I executed `sudo npm install -g git://github.com/reasonml/reason-cli.git#beta-v-1.13.3` on my home dir and got the following errors. (OSX 10.12.4)
```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "git://github.com/reasonml/reason-cli.git#beta-v-1.13.3"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! reason-cli@1.7.3 postinstall: `./performActualInstallAndFixLinks.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reason-cli@1.7.3 postinstall script './performActualInstallAndFixLinks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reason-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./performActualInstallAndFixLinks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reason-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reason-cli
npm ERR! There is likely additional logging output above.
```
more on [npm debug log](https://gist.github.com/437c6f8a7806e85300cf38ded8b7e173)

**Comment by jordwalke** [comment] 2017-05-01 08:48
Can you try uninstalling reason-cli and reinstalling it again?

**Comment by wangsongiam** [comment] 2017-05-01 09:07
@jordwalke Yes I executed the following commands in order:
1. `sudo npm uninstall -g git://github.com/reasonml/reason-cli.git#beta-v-1.13.3`

![2017-05-01 04 57 29](https://cloud.githubusercontent.com/assets/19645990/25576236/610668d4-2e2b-11e7-9b0b-d02d5e1affa6.gif)
2. `sudo npm install -g git://github.com/reasonml/reason-cli.git#beta-v-1.13.3`

![2017-05-01 04 58 07](https://cloud.githubusercontent.com/assets/19645990/25576262/90a27b32-2e2b-11e7-89a9-6c0c0e19abb1.gif)
3. `sudo yarn add global git://github.com/reasonml/reason-cli.git#beta-v-1.13.3`

![2017-05-01 04 58 57](https://cloud.githubusercontent.com/assets/19645990/25576277/a26cf2ca-2e2b-11e7-93b0-f11c1b243271.gif)
which got no error but got following lines when executing `refmt`
```
ERROR The following dependencies of package "reason-cli-actual" could not be resolved correctly:

  "@opam-alpha/reason", "ocaml", "ocamlBetterErrors" (and 2 more) packages


Did you forget to run "esy install" command?
Failed to get environment:
ERROR The following dependencies of package "reason-cli-actual" could not be resolved correctly:

  "@opam-alpha/reason", "ocaml", "ocamlBetterErrors" (and 2 more) packages


Did you forget to run "esy install" command?

```

**Comment by jordwalke** [comment] 2017-05-01 10:49
the instructions for reason-cli say to uninstall like `npm uninstall -g reason-cli`. Can you try that way just to rule out the possibility that it's not really uninstalling it?

**Comment by wangsongiam** [comment] 2017-05-01 21:07
Sorry,
`npm uninstall -g reason-cli` gave me nothing, and I got the same result after `npm install -g git://github.com/reasonml/reason-cli.git#beta-v-1.13.3` as in the instruction.

**Comment by jordwalke** [comment] 2017-05-02 02:48
Just to rule it out. Can you mv ~/.esy to somewhere else and try again?

**Comment by wangsongiam** [comment] 2017-05-02 02:54
ok, I moved ~/.esy to another folder, then tried reinstall it and got this error
```
Error: EACCES: permission denied, mkdir '/Users/wangsong/Library/Caches/Yarn'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Function.sync (/usr/local/lib/node_modules/reason-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/reason-cli/node_modules/esy/bin/yarn.js:30:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "git://github.com/reasonml/reason-cli.git#beta-v-1.13.3"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! reason-cli@1.7.3 postinstall: `./performActualInstallAndFixLinks.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reason-cli@1.7.3 postinstall script './performActualInstallAndFixLinks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reason-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./performActualInstallAndFixLinks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reason-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reason-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangsong/npm-debug.log

~ 23s
❯

```

**Comment by jordwalke** [comment] 2017-05-02 09:31
@andreypop and @bsansouci might have found the cause of this today. Did you recently upgrade to a new Mac OS?

**Comment by jordwalke** [comment] 2017-05-02 09:31
(just to unblock you, you can use the OPAM versions of reason until we figure this out).

**Comment by wangsongiam** [comment] 2017-05-02 17:06
Yes, about a week ago. 
Also, to make it clear, by using OPAM you mean `opam install reason` right?  Does it cover the same thing in NPM version?

**Comment by Korbin73** [comment] 2017-05-03 02:35
Installing from opam worked for me after it failed trying from npm with the same error as the OP.

**Comment by jordwalke** [comment] 2017-05-05 19:28
@wangsongiam Yes, opam installing reason covers most of the same things, but you also want to opam install merlin as well.

**Comment by gilbert** [comment] 2017-05-10 21:56
I tried installing today, and am getting the same error. I think this is the cause:

    error An unexpected error occurred: "http://gallium.inria.fr/~fpottier/menhir/menhir-20161115.tar.gz: Request failed \"404 Not Found\"".

**Comment by jordwalke** [comment] 2017-05-10 22:45
Thanks for the heads up @gilbert. Looks like menhir's page is down. I'm finding out what's going on, thanks.

**Comment by kristojorg** [comment] 2017-05-11 02:35
Is there a workaround for now that you know of? I installed via opam, and then ran `which ocamlmerlin refmt ocamlmerlin-reason` and it says none are found. Should I `opan install` each of these individually as well?

Thanks!

**Comment by gilbert** [comment] 2017-05-11 04:41
@kristojorg Installing this worked for me: https://github.com/yunxing/reason-bin

**Comment by jordwalke** [comment] 2017-05-11 04:47
reason-bin works if you just need to install the refmt binary for parsing/printing. Waiting on menhir to put their servers back up to make reason-cli work again. (Reason-cli is a best effort supported tool, but opam is better supported).

@kristojorg If you want to use opam, it should work - you probably don't have your shell setup correctly with the opam command you need to run etc. Is that true?

**Comment by jordwalke** [comment] 2017-05-11 08:53
This should be fixed now! Thanks for your patience. We'll try to get something that makes the open source reason-cli workflow more similar to the internal one.

**Closed by jordwalke** 2017-05-11 08:53 UTC

**Comment by nunobaba** [comment] 2017-09-27 02:37
I bumped on the same installation problem on Archlinux and yarn 1.11. Not sure why but the problem solved itself by running the same command twice: 
`yarn global add https://github.com/reasonml/reason-cli/archive/beta-v-1.13.7-bin-linux.tar.gz`
